<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

require_once __DIR__ . '/../init.php';
$pageTitle = "Report Generation"; 
$userName = $_SESSION['user_name'] ?? 'User';
?>   

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report Generation</title>
    <link rel="stylesheet" href="../assets/css/dashboard_style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.sheetjs.com/xlsx-latest/package/dist/xlsx.full.min.js"></script>

    <style>
        :root {
            --accent: #2563EB;
            --accent-light: #93C5FD;
            --white: #ffffff;
        }

        .btn-primary {
            background-color: var(--accent);
            border: none;
        }

        .btn-primary:hover {
            background-color: #1e4fd7;
        }

        .btn-secondary {
            background-color: #6c757d;
            border: none;
            color: #fff;
        }

        .btn-secondary:hover {
            background-color: #5a6268;
        }

        .table thead th {
            color: #2563EB;
            border-bottom: 2px solid #2563EB;
            font-weight: 600;
            text-align: center;
        }

        .table tbody td {
            text-align: center;
        }

        .table tbody tr:nth-child(odd) {
            background-color: #ffffff;
        }

        .table tbody tr:nth-child(even) {
            background-color: #F5F6FA;
        }

        .btn-export {
            border: 1.5px solid #2563EB;
            color: #2563EB;
            font-weight: 500;
        }

        .btn-export:hover {
            background-color: #2563EB;
            color: #ffffff;
        }

        .badge-success {
            background-color: #28a745 !important;
            color: #ffffff !important;
        }

        .badge-warning {
            background-color: #FFC107 !important;
            color: #2D3436 !important;
        }

        .badge-danger {
            background-color: #DC2626 !important;
            color: #ffffff !important;
        }

        .filters-container input,
        .filters-container select {
            border: 1px solid var(--accent);
            border-radius: 5px;
        }
    </style>
</head>

<body>
    <?php include __DIR__ . '/../includes/layout/sidebar.php'; ?>
    <?php include __DIR__ . '/../includes/layout/topbar.php'; ?>

    <div class="main-content p-5 mt-5">
        
        <!-- Filters Section -->
        <div class="d-flex align-items-center gap-2 flex-wrap mb-4 filters-container">
            <select id="reportType" class="form-select" 
                style="width: 180px; background-color: #93C5FD; color: #2563EB; border: none;">
                <option value="" disabled selected hidden>Report Type</option>
                <option value="attendance">Attendance</option>
                <option value="payroll">Payroll</option>
                <option value="overtime">Overtime</option>
                <option value="leave">Leave</option>
                <option value="performance">Performance</option>
            </select>

            <input type="date" id="dateFrom" class="form-control"
                style="width: 160px; background-color: #93C5FD; color: #2563EB; border: none;">
            <input type="date" id="dateTo" class="form-control"
                style="width: 160px; background-color: #93C5FD; color: #2563EB; border: none;">

            <button id="generateReport" class="btn btn-primary">Generate Report</button>
        </div>

                    <!-- Table Section -->
                    <div class="table-responsive">
                        <table class="table table-striped align-middle">
                            <thead class="table-light">
                                <tr class="text-center">
                                <th>Report Name</th>
                                <th>Report Type</th>
                                <th>Generated By</th>
                                <th>Department</th>
                                <th>Date Generated</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody id="reportTbody" class="text-center"></tbody>
                    </table>
                </div>
            
                    <!-- Footer -->
                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <div>
                            <div id="repPageInfo" class="mb-3" style="color: #5B5757"></div>
                            <div class="d-flex gap-2">
                                <button id="exportCsv" class="btn btn-export">
                                    <i class="bi bi-file-earmark-text me-1"></i> Export CSV
                                </button>
                                <button id="exportXls" class="btn btn-export">
                                    <i class="bi bi-file-earmark-spreadsheet me-1"></i> Export Excel
                                </button>
                            </div>
                        </div>

                        <nav aria-label="Page navigation">
                            <ul id="repPager" class="pagination mb-0"></ul>
                        </nav>
                    </div>

        <!-- Report Preview Modal -->
        <div class="modal fade" id="reportPreviewModal" tabindex="-1" aria-labelledby="reportPreviewLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header" style="border-bottom: 2px solid #2563EB; display: flex; justify-content: space-between; align-items: center;">
                        <h5 class="modal-title" id="reportPreviewLabel">Report Preview</h5>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" id="reportModalBody">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <script>
        function badgeHtml(s){
            if (s==='completed' || s==='approved') return '<span class="badge bg-success">Completed</span>';
            if (s==='pending') return '<span class="badge bg-warning text-dark">Pending</span>';
            if (s==='rejected') return '<span class="badge bg-danger">Rejected</span>';
            return '<span class="badge bg-secondary">Unknown</span>';
        }

        $(function(){
            const typeSel = document.getElementById('reportType');
            const dateFrom = document.getElementById('dateFrom');
            const dateTo = document.getElementById('dateTo');
            const genBtn = document.getElementById('generateReport');
            const tbody = document.getElementById('reportTbody');
            const pageInfo = document.getElementById('repPageInfo');
            const pager = document.getElementById('repPager');
            const expCsv = document.getElementById('exportCsv');
            const expXls = document.getElementById('exportXls');

            let rows = [];
            let page = 1;
            const limit = 10;

            function render(rowsPage, page, pages){
                tbody.innerHTML = rowsPage.map(r=>{
                    return `<tr data-id="${r.id}" data-type="${r.type}">
                        <td>${r.name}</td>
                        <td>${r.typeLabel}</td>
                        <td>${r.by}</td>
                        <td>${r.dept||''}</td>
                        <td>${r.date||''}</td>
                        <td>${badgeHtml(r.status)}</td>
                        <td>
                            <button class="btn btn-outline-primary btn-sm" data-action="preview"><i class="bi bi-eye"></i></button>
                        </td>
                    </tr>`;
                }).join('');
                if (pageInfo) pageInfo.textContent = `Showing Page ${page} of ${pages}`;
                if (pager) {
                    const items = [];
                    items.push(`<li class="page-item ${page===1?'disabled':''}"><a class="page-link" href="#" data-page="prev">Previous</a></li>`);
                    const start = Math.max(1, page-2);
                    const end = Math.min(pages, start+4);
                    for (let i=start;i<=end;i++){ items.push(`<li class="page-item ${i===page?'active':''}"><a class="page-link" href="#" data-page="${i}">${i}</a></li>`); }
                    items.push(`<li class="page-item ${page===pages?'disabled':''}"><a class="page-link" href="#" data-page="next">Next</a></li>`);
                    pager.innerHTML = items.join('');
                }
            }

            function paginate(){
                const total = rows.length;
                const pages = Math.max(1, Math.ceil(total/limit));
                const start = (page-1)*limit;
                render(rows.slice(start, start+limit), page, pages);
            }

            function toDate(s){ return s ? new Date(s) : null; }
            function fmtDate(s){ return s || ''; }
            function user(){ return (typeof window !== 'undefined') ? ('<?php echo $userName; ?>') : 'System'; }

            function buildRows(type, data, periodMap){
                const out = [];
                if (type==='payroll') {
                    data.forEach(r=>{
                        out.push({ id: r.payroll_id, type:'payroll', typeLabel:'Payroll', name: r.user_name||('Employee '+r.emp_id), by: user(), dept: r.dept_name||'', date: periodMap[r.payroll_period_id]||'', status: r.payroll_status||'pending' });
                    });
                } else if (type==='overtime') {
                    data.forEach(r=>{
                        out.push({ id: r.overtime_id, type:'overtime', typeLabel:'Overtime', name: 'Overtime #'+r.overtime_id, by: user(), dept: '', date: (r.date_from||'')+'–'+(r.date_to||''), status: r.status||'pending' });
                    });
                } else if (type==='leave') {
                    data.forEach(r=>{
                        out.push({ id: r.leave_id, type:'leave', typeLabel:'Leave', name: r.leave_type||('Leave #'+r.leave_id), by: user(), dept: '', date: (r.date_from||'')+'–'+(r.date_to||''), status: r.status||'pending' });
                    });
                } else if (type==='attendance') {
                    out.length = 0;
                } else if (type==='performance') {
                    out.length = 0;
                }
                return out;
            }

            function generate(){
                const type = typeSel ? typeSel.value : '';
                const df = dateFrom ? dateFrom.value : '';
                const dt = dateTo ? dateTo.value : '';
                if (!type) { tbody.innerHTML = '<tr><td colspan="7" class="text-center text-muted">Select a report type</td></tr>'; return; }
                tbody.innerHTML = '<tr><td colspan="7" class="text-center text-muted">Loading...</td></tr>';
                if (type==='payroll'){
                    $.getJSON('../modules/periods.php', { action:'list' }, function(rp){
                        const periods = (rp.data||[]).filter(p => (!df || new Date(p.end_date) >= new Date(df)) && (!dt || new Date(p.start_date) <= new Date(dt)));
                        const map = {}; periods.forEach(p=>{ map[p.period_id] = p.end_date; });
                        const reqs = periods.map(p=> $.getJSON('../modules/payroll.php', { action:'list', period_id:p.period_id }));
                        if (reqs.length===0){ rows = []; page=1; paginate(); return; }
                        $.when.apply($, reqs).done(function(){
                            const args = arguments.length===1 ? [arguments] : arguments;
                            const all = [];
                            for (let i=0;i<args.length;i++){ (args[i][0].data||[]).forEach(r=> all.push(r)); }
                            rows = buildRows('payroll', all, map); page=1; paginate();
                        });
                    });
                } else if (type==='overtime'){
                    $.getJSON('../modules/requests.php', { action:'list', type:'overtime', date_from: df||'', date_to: dt||'' }, function(ro){ rows = buildRows('overtime', ro.data||[], {}); page=1; paginate(); });
                } else if (type==='leave'){
                    $.getJSON('../modules/requests.php', { action:'list', type:'leave', date_from: df||'', date_to: dt||'' }, function(rl){ rows = buildRows('leave', rl.data||[], {}); page=1; paginate(); });
                } else {
                    rows = []; page=1; paginate();
                }
            }

            if (genBtn) genBtn.addEventListener('click', generate);
            if (pager) pager.addEventListener('click', function(e){ const a=e.target.closest('a.page-link'); if(!a) return; e.preventDefault(); const dp=a.getAttribute('data-page'); const totalPages=Math.max(1, Math.ceil(rows.length/limit)); if (dp==='prev') page=Math.max(1,page-1); else if (dp==='next') page=Math.min(totalPages,page+1); else page=parseInt(dp,10)||1; paginate(); });
            if (tbody) tbody.addEventListener('click', function(e){ const btn=e.target.closest('button'); if(!btn) return; const tr=btn.closest('tr'); const id=tr.getAttribute('data-id'); const type=tr.getAttribute('data-type'); const row = rows.find(r=>String(r.id)===String(id) && r.type===type); const content=`<div class="row g-3"><div class="col-md-6"><p><strong>Report Name:</strong> ${row.name}</p><p><strong>Report Type:</strong> ${row.typeLabel}</p></div><div class="col-md-6"><p><strong>Generated By:</strong> ${row.by}</p><p><strong>Department:</strong> ${row.dept||''}</p><p><strong>Date Generated:</strong> ${row.date||''}</p><p><strong>Status:</strong> ${badgeHtml(row.status)}</p></div></div>`; $('#reportModalBody').html(content); const m=new bootstrap.Modal(document.getElementById('reportPreviewModal')); m.show(); });

            // Helper to convert status badge to plain text
            function statusText(s){
                if(s === 'completed' || s === 'approved') return 'Completed';
                if(s === 'pending') return 'Pending';
                if(s === 'rejected') return 'Rejected';
                return 'Unknown';
            }

            // Export CSV
            function exportCsv(data){
                const cols = ['Report Name','Report Type','Generated By','Department','Date Generated','Status'];
                const lines = [cols.join(',')];

                data.forEach(r=>{
                    const line = [
                        r.name,
                        r.typeLabel,
                        r.by,
                        r.dept || '',
                        r.date || '',
                        statusText(r.status)
                    ].map(v => `"${String(v).replace(/"/g,'""')}"`).join(',');
                    lines.push(line);
                });

                const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8;' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = 'reports.csv';
                a.click();
                URL.revokeObjectURL(url);
            }

        function exportXls(data){
            const wsData = [
                ['Report Name','Report Type','Generated By','Department','Date Generated','Status'],
                ...data.map(r => [
                    r.name,
                    r.typeLabel,
                    r.by,
                    r.dept || '',
                    r.date || '',
                    statusText(r.status)
                ])
            ];

            const wb = XLSX.utils.book_new();
            const ws = XLSX.utils.aoa_to_sheet(wsData);

            // Apply Arial font to all cells
            const range = XLSX.utils.decode_range(ws['!ref']);
            for(let R = range.s.r; R <= range.e.r; ++R) {
                for(let C = range.s.c; C <= range.e.c; ++C) {
                    const cell_address = {c:C, r:R};
                    const cell_ref = XLSX.utils.encode_cell(cell_address);
                    if(!ws[cell_ref]) continue;
                    if(!ws[cell_ref].s) ws[cell_ref].s = {};
                    ws[cell_ref].s.font = { name: "Arial", sz: 11 };
                }
            }

    XLSX.utils.book_append_sheet(wb, ws, "Reports");
    XLSX.writeFile(wb, "reports.xlsx");
}

            // Bind export buttons
            if (expCsv) expCsv.addEventListener('click', function(){ exportCsv(rows); });
            if (expXls) expXls.addEventListener('click', function(){ exportXls(rows); });

            rows = []; paginate();
        });
    </script>

</body>
</html>